const express = require('express');
const auth = require('../middleware/auth');
const Donor = require('../models/Donor');
const Campaign = require('../models/Campaign');
const Emergency = require('../models/Emergency');
const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const fs = require('fs');
const path = require('path');

const router = express.Router();

const sampleMonths = [
  { month: 'Jan', donations: 120, donors: 90 },
  { month: 'Feb', donations: 150, donors: 100 },
  { month: 'Mar', donations: 180, donors: 130 },
];

function toCSV(rows) {
  if (!rows || rows.length === 0) return '';
  const keys = Object.keys(rows[0]);
  const lines = [keys.join(',')];
  for (const r of rows) {
    lines.push(keys.map(k => JSON.stringify(r[k] ?? '')).join(','));
  }
  return lines.join('\n');
}

router.get('/export/csv', auth, async (req, res) => {
  const type = req.query.type || 'donor';
  try {
    let rows = [];
    if (type === 'donor') {
      const docs = await Donor.find().lean().limit(1000);
      rows = docs.map(d => ({ name: d.name, phone: d.phone, bloodGroup: d.bloodGroup, donations: d.donations, lastDonationDate: d.lastDonationDate }));
    } else if (type === 'campaign') {
      const docs = await Campaign.find().lean().limit(1000);
      rows = docs.map(c => ({ title: c.title, status: c.status, engagement: c.performance?.engagement }));
    } else if (type === 'hospital') {
      const docs = await Emergency.find().lean().limit(1000);
      rows = docs.map(h => ({ location: h.location, urgencyLevel: h.urgencyLevel, unitsNeeded: h.unitsNeeded }));
    } else {
      rows = sampleMonths;
    }

    const csv = toCSV(rows);
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="report-${type}.csv"`);
    return res.send(csv);
  } catch (err) {
    console.error('reports/export/csv error', err && err.message);
    return res.status(500).json({ message: 'Failed to generate CSV' });
  }
});

router.get('/export/pdf', auth, async (req, res) => {
  const type = req.query.type || 'donor';
  const includeWatermark = String(req.query.watermark || 'false').toLowerCase() === 'true';
  try {
    let rows = [];
    if (type === 'donor') {
      const docs = await Donor.find().lean().limit(500);
      rows = docs.map(d => ({ name: d.name, phone: d.phone, bloodGroup: d.bloodGroup, donations: d.donations }));
    } else if (type === 'campaign') {
      const docs = await Campaign.find().lean().limit(500);
      rows = docs.map(c => ({ title: c.title, status: c.status }));
    } else if (type === 'hospital') {
      const docs = await Emergency.find().lean().limit(500);
      rows = docs.map(h => ({ location: h.location, urgencyLevel: h.urgencyLevel }));
    } else {
      rows = sampleMonths;
    }

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="report-${type}.pdf"`);

    const doc = new PDFDocument({ margin: 36, size: 'A4', autoFirstPage: false });
    doc.pipe(res);

    // header + logo
    const logoPath = path.resolve(__dirname, '../assets/logo.png');
    const createPage = () => {
      doc.addPage();
      if (fs.existsSync(logoPath)) {
        try { doc.image(logoPath, 36, 28, { width: 100 }); } catch (e) { /* ignore */ }
      } else {
        // simple text logo
        doc.fillColor('#ef4444').fontSize(20).text('BloodConnect', 36, 32);
      }
      doc.fillColor('#ffffff');
      doc.fontSize(12).text('Generated by BloodConnect CRM', { align: 'right', continued: false });
      doc.moveDown(2);
    };

    // footer with page numbers
    const drawFooter = () => {
      const bottom = doc.page.height - 40;
      doc.fontSize(9).fillColor('#94a3b8');
      doc.text('Generated by BloodConnect CRM.', 36, bottom, { align: 'left' });
      const pageNum = `Page ${doc.page.number}`;
      doc.text(pageNum, 0, bottom, { align: 'right' });
    };

    // watermark (optional)
    const drawWatermark = () => {
      if (!includeWatermark) return;
      const txt = 'Confidential - BloodConnect';
      doc.save();
      doc.rotate(-45, { origin: [doc.page.width / 2, doc.page.height / 2] });
      doc.fontSize(60).fillColor('rgba(255,255,255,0.06)').text(txt, doc.page.width / 6, doc.page.height / 3, { align: 'center' });
      doc.restore();
    };

    // first page
    createPage();
    drawWatermark();
    doc.moveDown(2);
    doc.fontSize(18).fillColor('#ffffff').text(`Report - ${type}`, { underline: true });
    doc.moveDown();

    // summary
    doc.fontSize(11).fillColor('#cbd5e1').text(`Total rows: ${rows.length}`);
    doc.moveDown(0.5);

    // table header
    const headers = Object.keys(rows[0] || {});
    const tableTop = doc.y + 6;
    const colWidths = headers.map(() => Math.floor((doc.page.width - 72) / headers.length));
    // header row
    doc.fontSize(10).fillColor('#ffffff');
    headers.forEach((h, i) => {
      doc.rect(36 + colWidths.slice(0, i).reduce((s, v) => s + v, 0), tableTop - 4, colWidths[i], 20).fill('#8b5cf6');
    });
    headers.forEach((h, i) => {
      doc.fillColor('#ffffff').text(h.toUpperCase(), 38 + colWidths.slice(0, i).reduce((s, v) => s + v, 0), tableTop, { width: colWidths[i] - 8 });
    });
    doc.moveDown(1.8);

    // rows with alternating background
    let rowY = doc.y;
    let alternate = false;
    for (let rIndex = 0; rIndex < rows.length; rIndex++) {
      const row = rows[rIndex];
      const rowTop = rowY;
      if (alternate) {
        doc.rect(36, rowTop - 2, doc.page.width - 72, 18).fill('#0b1220');
      }
      let offsetX = 0;
      headers.forEach((h, i) => {
        doc.fillColor('#e2e8f0').fontSize(10).text(String(row[h] ?? ''), 38 + offsetX, rowTop, { width: colWidths[i] - 8 });
        offsetX += colWidths[i];
      });
      rowY += 18;
      doc.y = rowY;
      alternate = !alternate;
      // add new page if near bottom
      if (doc.y > doc.page.height - 80) {
        drawFooter();
        createPage();
        drawWatermark();
        rowY = doc.y;
      }
    }

    drawFooter();
    doc.end();
  } catch (err) {
    console.error('reports/export/pdf error', err && err.message);
    return res.status(500).json({ message: 'Failed to generate PDF' });
  }
});

router.get('/export/excel', auth, async (req, res) => {
  // retained for backward compatibility; prefer /export/xlsx
  const type = req.query.type || 'donor';
  try {
    let rows = [];
    if (type === 'donor') {
      const docs = await Donor.find().lean().limit(1000);
      rows = docs.map(d => ({ name: d.name, phone: d.phone, bloodGroup: d.bloodGroup, donations: d.donations }));
    } else if (type === 'campaign') {
      const docs = await Campaign.find().lean().limit(1000);
      rows = docs.map(c => ({ title: c.title, status: c.status }));
    } else if (type === 'hospital') {
      const docs = await Emergency.find().lean().limit(1000);
      rows = docs.map(h => ({ location: h.location, urgencyLevel: h.urgencyLevel }));
    } else {
      rows = sampleMonths;
    }

    // create a simple workbook using exceljs
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Report');
    if (rows.length > 0) {
      const keys = Object.keys(rows[0]);
      sheet.addRow(keys.map(k => k.toString().toUpperCase()));
      // style header
      const headerRow = sheet.getRow(1);
      headerRow.font = { bold: true };
      headerRow.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFA78BFA' } };
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
      });
      // add rows
      rows.forEach(r => sheet.addRow(Object.values(r)));
      // totals row for numeric columns
      const lastRowIdx = sheet.rowCount + 1;
      const totals = [];
      keys.forEach((k, idx) => {
        const col = idx + 1;
        const colValues = rows.map(r => typeof r[k] === 'number' ? r[k] : null).filter(v => v !== null);
        if (colValues.length > 0) {
          const sum = colValues.reduce((s, v) => s + v, 0);
          totals.push(sum);
          sheet.getColumn(col).numFmt = '#,##0';
        } else {
          totals.push('');
        }
      });
      sheet.addRow(totals);
      // auto-size columns
      sheet.columns.forEach((column) => {
        let maxLength = 10;
        column.eachCell({ includeEmpty: true }, (cell) => {
          const v = cell.value ? cell.value.toString() : '';
          maxLength = Math.max(maxLength, v.length + 2);
        });
        column.width = Math.min(maxLength, 60);
      });
    }

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="report-${type}.xlsx"`);
    await workbook.xlsx.write(res);
    res.end();
  } catch (err) {
    console.error('reports/export/excel error', err && err.message);
    return res.status(500).json({ message: 'Failed to generate Excel' });
  }
});

// New modern xlsx endpoint with multiple sheets support
router.get('/export/xlsx', auth, async (req, res) => {
  const type = req.query.type || 'donor';
  try {
    const workbook = new ExcelJS.Workbook();
    // donors sheet
    if (type === 'donor' || type === 'all') {
      const docs = await Donor.find().lean().limit(5000);
      const sheet = workbook.addWorksheet('Donors');
      sheet.columns = [
        { header: 'Name', key: 'name' },
        { header: 'Phone', key: 'phone' },
        { header: 'Blood Group', key: 'bloodGroup' },
        { header: 'Donations', key: 'donations' },
        { header: 'Last Donation', key: 'lastDonationDate' },
      ];
      sheet.getRow(1).font = { bold: true };
      sheet.getRow(1).eachCell((c)=>{ c.fill = { type:'pattern', pattern:'solid', fgColor:{argb:'FF8B5CF6'} }; });
      docs.forEach(d => sheet.addRow({ name: d.name, phone: d.phone, bloodGroup: d.bloodGroup, donations: d.donations, lastDonationDate: d.lastDonationDate }));
      // totals
      const totalDonations = docs.reduce((s, d) => s + (d.donations || 0), 0);
      sheet.addRow([]);
      const totalRow = sheet.addRow(['', '', 'Total', totalDonations, '']);
      totalRow.font = { bold: true };
      sheet.columns.forEach((col) => { let maxLen = 10; col.eachCell(c=>{ const v = c.value ? c.value.toString() : ''; maxLen = Math.max(maxLen, v.length + 2); }); col.width = Math.min(maxLen, 60); });
    }

    if (type === 'campaign' || type === 'all') {
      const docs = await Campaign.find().lean().limit(2000);
      const sheet = workbook.addWorksheet('Campaigns');
      sheet.columns = [ { header: 'Title', key: 'title' }, { header: 'Status', key: 'status' }, { header: 'Engagement', key: 'engagement' } ];
      sheet.getRow(1).font = { bold: true };
      sheet.getRow(1).eachCell((c)=>{ c.fill = { type:'pattern', pattern:'solid', fgColor:{argb:'FF8B5CF6'} }; });
      docs.forEach(d => sheet.addRow({ title: d.title, status: d.status, engagement: d.performance?.engagement }));
      sheet.columns.forEach((col) => { let maxLen = 10; col.eachCell(c=>{ const v = c.value ? c.value.toString() : ''; maxLen = Math.max(maxLen, v.length + 2); }); col.width = Math.min(maxLen, 60); });
    }

    if (type === 'hospital' || type === 'all') {
      const docs = await Emergency.find().lean().limit(2000);
      const sheet = workbook.addWorksheet('Hospitals');
      sheet.columns = [ { header: 'Location', key: 'location' }, { header: 'Urgency', key: 'urgencyLevel' }, { header: 'UnitsNeeded', key: 'unitsNeeded' } ];
      sheet.getRow(1).font = { bold: true };
      sheet.getRow(1).eachCell((c)=>{ c.fill = { type:'pattern', pattern:'solid', fgColor:{argb:'FF8B5CF6'} }; });
      docs.forEach(d => sheet.addRow({ location: d.location, urgencyLevel: d.urgencyLevel, unitsNeeded: d.unitsNeeded }));
      sheet.columns.forEach((col) => { let maxLen = 10; col.eachCell(c=>{ const v = c.value ? c.value.toString() : ''; maxLen = Math.max(maxLen, v.length + 2); }); col.width = Math.min(maxLen, 60); });
    }

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="report-${type}.xlsx"`);
    await workbook.xlsx.write(res);
    res.end();
  } catch (err) {
    console.error('reports/export/xlsx error', err && err.message);
    return res.status(500).json({ message: 'Failed to generate XLSX' });
  }
});

router.get('/drilldown', auth, async (req, res) => {
  const { month, type } = req.query;
  const page = parseInt(req.query.page, 10) || 1;
  const pageSize = parseInt(req.query.pageSize, 10) || 50;
  try {
    if (type === 'donor') {
      // filter donors by lastDonationDate month if provided
      const match = {};
      if (month) {
        // simple month name match against ISO month
        const monthNames = { Jan:0, Feb:1, Mar:2, Apr:3, May:4, Jun:5, Jul:6, Aug:7, Sep:8, Oct:9, Nov:10, Dec:11 };
        const m = monthNames[String(month).slice(0,3)];
        if (typeof m === 'number') {
          const start = new Date(new Date().getFullYear(), m, 1);
          const end = new Date(new Date().getFullYear(), m+1, 1);
          match.lastDonationDate = { $gte: start, $lt: end };
        }
      }
      const total = await Donor.countDocuments(match);
      const rows = await Donor.find(match).skip((page-1)*pageSize).limit(pageSize).lean();
      return res.json({ rows: rows.map(r=>({ donor: r.name, amount: r.donations, date: r.lastDonationDate })), total });
    }

    // fallback: return campaign or emergency items
    if (type === 'campaign') {
      const total = await Campaign.countDocuments();
      const rows = await Campaign.find().skip((page-1)*pageSize).limit(pageSize).lean();
      return res.json({ rows, total });
    }

    if (type === 'hospital') {
      const total = await Emergency.countDocuments();
      const rows = await Emergency.find().skip((page-1)*pageSize).limit(pageSize).lean();
      return res.json({ rows, total });
    }

    return res.json({ rows: sampleMonths, total: sampleMonths.length });
  } catch (err) {
    console.error('reports/drilldown error', err && err.message);
    return res.status(500).json({ message: 'Failed to fetch drilldown' });
  }
});

module.exports = router;
