import React from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Users, BarChart2, Award, Calendar, MessageSquare, Zap } from 'lucide-react';

const Card = ({ title, desc, Icon, to }: any) => {
  const navigate = useNavigate();
  return (
    <motion.button
      whileHover={{ scale: 1.03 }}
      whileTap={{ scale: 0.98 }}
      onClick={() => navigate(to)}
      className="group relative cursor-pointer rounded-2xl p-6 shadow-2xl transform-gpu bg-gradient-to-br from-red-500/10 to-purple-700/10 border border-white/5 backdrop-blur-md hover:shadow-[0_8px_30px_rgba(139,92,246,0.12)] transition"
    >
      <div className="flex items-center gap-4">
        <div className="rounded-full p-3 bg-gradient-to-br from-red-500 to-violet-600 text-white shadow-lg group-hover:scale-105 transition">
          <Icon className="h-6 w-6" />
        </div>
        <div className="text-left">
          <div className="text-sm font-semibold text-white">{title}</div>
          <div className="mt-1 text-xs text-slate-300">{desc}</div>
        </div>
      </div>
      <div className="absolute right-4 top-4 text-xs text-rose-400 opacity-0 group-hover:opacity-100 transition">Open →</div>
    </motion.button>
  );
};

const VolunteerLanding: React.FC = () => {
  return (
    <div className="min-h-screen p-6">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-extrabold text-white">Volunteer Command Center</h1>
          <p className="text-sm text-slate-300">Futuristic hub to manage volunteers and rewards</p>
        </div>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <Card
          title="Volunteer Profiles"
          desc="Manage avatars, contact and activity history"
          Icon={Users}
          to="/app/volunteers/profiles"
        />

        <Card
          title="Engagement Metrics"
          desc="Hours, campaigns joined, referrals"
          Icon={BarChart2}
          to="/app/volunteers/metrics"
        />

        <Card
          title="Reward Program"
          desc="Points, badges and milestones"
          Icon={Award}
          to="/app/volunteers/rewards"
        />

        <Card
          title="Upcoming Events"
          desc="Calendar view for drives and campaigns"
          Icon={Calendar}
          to="/app/volunteers/events"
        />

        <Card
          title="Communication Hub"
          desc="WhatsApp, SMS, Email — reach out with one click"
          Icon={MessageSquare}
          to="/app/volunteers/comm"
        />

        <Card
          title="AI Suggestions"
          desc="Re-engagement ideas generated by AI"
          Icon={Zap}
          to="/app/volunteers/ai"
        />
      </div>
    </div>
  );
};

export default VolunteerLanding;
